apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-app
    env: dev
spec:
  containers:
  - name: demoapp-container
    image: busybox:latest
    env:
    - name: DEMO_ENV
      value: dev
    command: ['sh', '-c', 'echo "Running the main application..."; sleep 10; echo "Main application complete."']
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"
  initContainers:
  - name: init-demoapp-container
    image: busybox:latest
    command: ['sh', '-c', 'echo "Initializing the application..."; sleep 60; echo "Initialization complete."']
    env:
    - name: INIT_ENV
      value: init-dev
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  