apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-a
  name: nginx-a
spec:
  containers:
  - image: nginx
    name: nginx-a
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodetype
            operator: In
            values:
            - "highmem"
            - "highvol"

